#pragma once

#define ASIO_STANDALONE
#define ASIO_HAS_STD_ADDRESSOF
#define ASIO_HAS_STD_ARRAY
#define ASIO_HAS_CSTDINT
#define ASIO_HAS_STD_SHARED_PTR
#define ASIO_HAS_STD_TYPE_TRAITS

#define ASIO_HAS_STD_CHRONO

//#define BOOST_ASIO_STANDALONE
//#define BOOST_ASIO_HAS_STD_ADDRESSOF
//#define BOOST_ASIO_HAS_STD_ARRAY
//#define BOOST_ASIO_HAS_CSTDINT
//#define BOOST_ASIO_HAS_STD_SHARED_PTR
//#define BOOST_ASIO_HAS_STD_TYPE_TRAITS

//#define ASIO_ENABLE_BUFFER_DEBUGGING
//#define ASIO_DISABLE_BUFFER_DEBUGGING.

//#define ASIO_ENABLE_HANDLER_TRACKING

#include <asio\asio.hpp>


